services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data
    networks:
      - app-network

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

  garage:
    image: dxflrs/garage:v2.2.0
    volumes:
      - ./docker/garage.toml:/etc/garage.toml:ro
      - garage_data:/var/lib/garage
    restart: unless-stopped
    ports:
      - '3900:3900'
      - '3901:3901'
      - '3902:3902'
      - '3903:3903'
    networks:
      - app-network
    environment:
      - RUST_LOG=info

  garage-webui:
    image: khairul169/garage-webui:latest
    restart: unless-stopped
    ports:
      - '3909:80'
    environment:
      - AUTH_USER_PASS=admin:admin
      - API_BASE_URL=http://localhost:3900
      - S3_ENDPOINT_URL=http://localhost:3900
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    volumes:
      - mailpit_data:/data
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  mailpit_data:
  garage_data:

networks:
  app-network:
    driver: bridge
